apiVersion: v1
kind: Service
metadata:
{{- if .Values.replaceLegacyService }}
  # use the old name of rest api to avoid changes in team applications
  name: clamav 
{{- else }}
  name: {{ include "clamav-rest.fullname" . | nindent 4 }}
{{- end }}
  labels:
    {{- include "clamav-rest.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    {{- include "clamav-rest.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
