environmentKinds:
  - tenant
  - onprem
values:
  maxFileSize:
    displayName: Max file size allowed
    description: Max file size allowed for scanning (should be the same value as in clamd.conf)
    config:
      type: string
  replaceLegacyService:
    displayName: Use the original service name
    description: Temporary switch to ease migration to new rest api, set this to enable the new api
    config:
      type: bool
    
